// import { GovernmentService, ServiceCategoryTab } from '../models/service.model';

import { GovernmentService, ServiceCategoryTab } from "../Utilities/Interfaces/IService";

export const SERVICE_CATEGORIES: ServiceCategoryTab[] = [
  { id: 'all', label: 'الكل', route: '/services', icon: 'bi-grid-fill' },
  { id: 'traffic', label: 'المرور', route: '/services/traffic', icon: 'bi-car-front-fill' },
  { id: 'civil-status', label: 'الأحوال المدنية', route: '/services/civil-status', icon: 'bi-person-vcard-fill' },
//   { id: 'passports', label: 'الجوازات والهجرة', route: '/services/passports', icon: 'bi-airplane-fill' },
//   { id: 'supply', label: 'التموين', route: '/services/supply', icon: 'bi-basket3-fill' },
//   { id: 'education', label: 'التعليم', route: '/services/education', icon: 'bi-mortarboard-fill' },
//   { id: 'health', label: 'الصحة', route: '/services/health', icon: 'bi-heart-pulse-fill' },
];

export const GOVERNMENT_SERVICES: GovernmentService[] = [
  // ── TRAFFIC ──────────────────────────────────────────────────────────────
  {
    id: 'driving-license-renewal',
    title: 'تجديد رخصة القيادة',
    description: 'تجديد رخصة القيادة عبر بوابة المرور الإلكترونية دون الحاجة للحضور',
    category: 'traffic',
    icon: 'bi-car-front-fill',
    estimatedTime: '3 - 5 أيام عمل',
    fees: '155 جنيه',
    processingMinutes: 20,
    documentsCount: 4,
    documents: [
      { name: 'بطاقة الرقم القومي سارية', required: true },
      { name: 'رخصة القيادة الحالية', required: true },
      { name: 'شهادة اللياقة الطبية', required: true },
      { name: 'صور شخصية حديثة (2 صور)', required: true },
    ],
    steps: [
      { order: 1, description: 'تسجيل الدخول إلى بوابة المرور الإلكترونية' },
      { order: 2, description: 'اختيار خدمة "تجديد رخصة القيادة"' },
      { order: 3, description: 'إدخال بيانات الرخصة والرقم القومي' },
      { order: 4, description: 'رفع المستندات المطلوبة' },
      { order: 5, description: 'سداد الرسوم إلكترونياً' },
      { order: 6, description: 'استلام الرخصة بالبريد أو الحضور للاستلام' },
    ],
  },
  {
    id: 'new-driving-license',
    title: 'استخراج رخصة قيادة',
    description: 'استخراج رخصة قيادة جديدة لأول مرة من إدارة المرور',
    category: 'traffic',
    icon: 'bi-car-front-fill',
    estimatedTime: '7 - 10 أيام عمل',
    fees: '220 جنيه',
    processingMinutes: 45,
    documentsCount: 5,
    documents: [
      { name: 'بطاقة الرقم القومي', required: true },
      { name: 'شهادة اللياقة الطبية من طبيب معتمد', required: true },
      { name: 'صور شخصية (4 صور)', required: true },
      { name: 'شهادة إتمام دورة تعليم القيادة', required: true },
      { name: 'إيصال سداد الرسوم', required: true },
    ],
    steps: [
      { order: 1, description: 'حضور دورة تعليم القيادة في مدرسة معتمدة' },
      { order: 2, description: 'اجتياز اختبار القيادة النظري والعملي' },
      { order: 3, description: 'تقديم الطلب وإرفاق المستندات' },
      { order: 4, description: 'سداد الرسوم المقررة' },
      { order: 5, description: 'استلام رخصة القيادة' },
    ],
  },
  {
    id: 'lost-driving-license',
    title: 'استخراج بدل فاقد رخصة',
    description: 'استخراج بدل فاقد لرخصة القيادة بسهولة عبر المنظومة الإلكترونية',
    category: 'traffic',
    icon: 'bi-car-front-fill',
    estimatedTime: '2 - 4 أيام عمل',
    fees: '75 جنيه',
    processingMinutes: 15,
    documentsCount: 3,
    documents: [
      { name: 'بطاقة الرقم القومي', required: true },
      { name: 'محضر الفقدان من الشرطة', required: true },
      { name: 'صور شخصية حديثة (2 صور)', required: true },
    ],
    steps: [
      { order: 1, description: 'تقديم بلاغ فقدان في أقرب قسم شرطة' },
      { order: 2, description: 'التوجه لإدارة المرور بالمستندات المطلوبة' },
      { order: 3, description: 'تعبئة نموذج الطلب وسداد الرسوم' },
      { order: 4, description: 'استلام الرخصة البديلة' },
    ],
  },
  {
    id: 'vehicle-license-renewal',
    title: 'تجديد رخصة مركبة',
    description: 'تجديد رخصة المركبة عبر البوابة الإلكترونية بدون الحاجة للحضور الشخصي',
    category: 'traffic',
    icon: 'bi-truck-front-fill',
    estimatedTime: '1 - 3 أيام عمل',
    fees: '180 جنيه',
    processingMinutes: 10,
    documentsCount: 3,
    documents: [
      { name: 'رخصة المركبة الحالية', required: true },
      { name: 'بطاقة الرقم القومي لصاحب السيارة', required: true },
      { name: 'شهادة الفحص الدوري للمركبة', required: true },
    ],
    steps: [
      { order: 1, description: 'إجراء الفحص الدوري للمركبة في محطة معتمدة' },
      { order: 2, description: 'تسجيل الدخول لبوابة المرور' },
      { order: 3, description: 'إدخال بيانات المركبة ورقم اللوحة' },
      { order: 4, description: 'سداد الرسوم إلكترونياً' },
      { order: 5, description: 'استلام الرخصة بالبريد' },
    ],
  },

  // ── CIVIL STATUS ─────────────────────────────────────────────────────────
  {
    id: 'national-id-renewal',
    title: 'تجديد بطاقة الرقم القومي',
    description: 'تجديد بطاقة الرقم القومي في دقائق عبر البوابة الإلكترونية بدون طوابير',
    category: 'civil-status',
    icon: 'bi-person-vcard-fill',
    estimatedTime: '3 - 7 أيام عمل',
    fees: '50 جنيه',
    processingMinutes: 15,
    documentsCount: 3,
    documents: [
      { name: 'البطاقة الحالية منتهية الصلاحية', required: true },
      { name: 'شهادة الميلاد الأصلية', required: true },
      { name: 'صور شخصية حديثة (4 صور)', required: true },
    ],
    steps: [
      { order: 1, description: 'تسجيل الدخول لبوابة الأحوال المدنية' },
      { order: 2, description: 'اختيار خدمة تجديد البطاقة وإدخال البيانات' },
      { order: 3, description: 'رفع صورة البطاقة الحالية والمستندات' },
      { order: 4, description: 'سداد رسوم 50 جنيه إلكترونياً' },
      { order: 5, description: 'استلام البطاقة بالبريد خلال المدة المحددة' },
    ],
  },
  {
    id: 'new-national-id',
    title: 'استخراج بطاقة رقم قومي لأول مرة',
    description: 'استخراج بطاقة الرقم القومي لأول مرة عند بلوغ سن 16 عاماً',
    category: 'civil-status',
    icon: 'bi-person-vcard-fill',
    estimatedTime: '5 - 10 أيام عمل',
    fees: '35 جنيه',
    processingMinutes: 30,
    documentsCount: 4,
    documents: [
      { name: 'شهادة الميلاد الأصلية', required: true },
      { name: 'صورة بطاقة ولي الأمر', required: true },
      { name: 'صور شخصية حديثة (4 صور)', required: true },
      { name: 'شهادة من المدرسة أو جهة التعليم', required: false },
    ],
    steps: [
      { order: 1, description: 'الحضور الشخصي لمكتب الأحوال المدنية' },
      { order: 2, description: 'تقديم المستندات وتعبئة الطلب' },
      { order: 3, description: 'أخذ البصمة والصورة الشخصية' },
      { order: 4, description: 'سداد الرسوم' },
      { order: 5, description: 'استلام البطاقة' },
    ],
  },
  {
    id: 'birth-certificate',
    title: 'استخراج شهادة ميلاد',
    description: 'استخراج نسخة رسمية من شهادة الميلاد إلكترونياً بدون الحاجة للحضور',
    category: 'civil-status',
    icon: 'bi-file-earmark-text-fill',
    estimatedTime: '1 - 2 يوم عمل',
    fees: '25 جنيه',
    processingMinutes: 10,
    documentsCount: 2,
    documents: [
      { name: 'بطاقة الرقم القومي', required: true },
      { name: 'رقم قيد الميلاد (إن وجد)', required: false },
    ],
    steps: [
      { order: 1, description: 'الدخول لبوابة استخراج الوثائق المدنية' },
      { order: 2, description: 'إدخال بيانات الشخص المراد استخراج شهادته' },
      { order: 3, description: 'التحقق من البيانات وسداد الرسوم' },
      { order: 4, description: 'تنزيل الشهادة إلكترونياً أو استلامها بالبريد' },
    ],
  },
  {
    id: 'family-record',
    title: 'استخراج قيد عائلي',
    description: 'استخراج قيد عائلي يتضمن بيانات جميع أفراد الأسرة رسمياً',
    category: 'civil-status',
    icon: 'bi-people-fill',
    estimatedTime: '2 - 5 أيام عمل',
    fees: '35 جنيه',
    processingMinutes: 20,
    documentsCount: 2,
    documents: [
      { name: 'بطاقة الرقم القومي لرب الأسرة', required: true },
      { name: 'عقد الزواج (للمتزوجين)', required: false },
    ],
    steps: [
      { order: 1, description: 'تسجيل الدخول وتحديد نوع الوثيقة' },
      { order: 2, description: 'إدخال بيانات رب الأسرة' },
      { order: 3, description: 'مراجعة البيانات وسداد الرسوم' },
      { order: 4, description: 'استلام القيد العائلي' },
    ],
  },
  {
    id: 'death-certificate',
    title: 'استخراج شهادة وفاة',
    description: 'استخراج شهادة وفاة رسمية معتمدة إلكترونياً من سجلات الأحوال المدنية',
    category: 'civil-status',
    icon: 'bi-file-earmark-medical-fill',
    estimatedTime: '1 - 3 أيام عمل',
    fees: '25 جنيه',
    processingMinutes: 15,
    documentsCount: 2,
    documents: [
      { name: 'بطاقة رقم قومي مقدم الطلب', required: true },
      { name: 'ما يثبت صلة القرابة بالمتوفى', required: true },
    ],
    steps: [
      { order: 1, description: 'الدخول لبوابة الأحوال المدنية' },
      { order: 2, description: 'اختيار خدمة شهادة الوفاة وإدخال بيانات المتوفى' },
      { order: 3, description: 'التحقق وسداد الرسوم' },
      { order: 4, description: 'استلام الشهادة' },
    ],
  },

  // ── PASSPORTS ────────────────────────────────────────────────────────────
//   {
//     id: 'passport-renewal',
//     title: 'تجديد جواز السفر',
//     description: 'تجديد جواز السفر بسهولة دون الحاجة للانتظار لفترات طويلة',
//     category: 'passports',
//     icon: 'bi-airplane-fill',
//     estimatedTime: '7 - 14 يوم عمل',
//     fees: '600 جنيه',
//     processingMinutes: 30,
//     documentsCount: 4,
//     documents: [
//       { name: 'الجواز الحالي (ساري أو منتهي)', required: true },
//       { name: 'بطاقة الرقم القومي', required: true },
//       { name: 'صور شخصية على خلفية بيضاء (4 صور)', required: true },
//       { name: 'إيصال سداد الرسوم', required: true },
//     ],
//     steps: [
//       { order: 1, description: 'تسجيل الدخول لبوابة الجوازات والهجرة' },
//       { order: 2, description: 'تقديم طلب التجديد وإدخال البيانات' },
//       { order: 3, description: 'رفع المستندات المطلوبة' },
//       { order: 4, description: 'سداد رسوم التجديد' },
//       { order: 5, description: 'الحضور لأخذ البصمة والصورة (إن طُلب)' },
//       { order: 6, description: 'استلام الجواز بالبريد أو من المقر' },
//     ],
//   },
//   {
//     id: 'new-passport',
//     title: 'استخراج جواز سفر جديد',
//     description: 'استخراج جواز سفر جديد لأول مرة بخطوات بسيطة عبر الإنترنت',
//     category: 'passports',
//     icon: 'bi-airplane-fill',
//     estimatedTime: '14 - 21 يوم عمل',
//     fees: '800 جنيه',
//     processingMinutes: 45,
//     documentsCount: 4,
//     documents: [
//       { name: 'بطاقة الرقم القومي سارية', required: true },
//       { name: 'شهادة الميلاد الأصلية', required: true },
//       { name: 'صور شخصية على خلفية بيضاء (6 صور)', required: true },
//       { name: 'إيصال سداد الرسوم', required: true },
//     ],
//     steps: [
//       { order: 1, description: 'تقديم الطلب عبر البوابة الإلكترونية' },
//       { order: 2, description: 'تحديد موعد للحضور الشخصي' },
//       { order: 3, description: 'تقديم المستندات وأخذ البصمة' },
//       { order: 4, description: 'سداد الرسوم المقررة' },
//       { order: 5, description: 'استلام الجواز' },
//     ],
//   },
//   {
//     id: 'lost-passport',
//     title: 'استخراج بدل فاقد جواز سفر',
//     description: 'استخراج بدل فاقد جواز السفر عبر الإجراءات الرسمية المعتمدة',
//     category: 'passports',
//     icon: 'bi-airplane-fill',
//     estimatedTime: '10 - 20 يوم عمل',
//     fees: '1000 جنيه',
//     processingMinutes: 60,
//     documentsCount: 5,
//     documents: [
//       { name: 'بطاقة الرقم القومي', required: true },
//       { name: 'محضر فقدان جواز السفر من الشرطة', required: true },
//       { name: 'صور شخصية (6 صور)', required: true },
//       { name: 'شهادة الميلاد', required: true },
//       { name: 'تقرير من السفارة إن فُقد في الخارج', required: false },
//     ],
//     steps: [
//       { order: 1, description: 'الإبلاغ عن الفقدان في أقرب قسم شرطة' },
//       { order: 2, description: 'تقديم طلب البدل وإرفاق محضر الفقدان' },
//       { order: 3, description: 'دفع الرسوم الإضافية المقررة' },
//       { order: 4, description: 'الحضور الشخصي لاستكمال الإجراءات' },
//       { order: 5, description: 'استلام جواز السفر البديل' },
//     ],
//   },

  // ── SUPPLY ───────────────────────────────────────────────────────────────
//   {
//     id: 'add-family-supply',
//     title: 'إضافة أفراد للبطاقة التموينية',
//     description: 'إضافة مواليد جدد أو أفراد جدد للبطاقة التموينية إلكترونياً',
//     category: 'supply',
//     icon: 'bi-basket3-fill',
//     estimatedTime: '2 - 5 أيام عمل',
//     fees: 'مجاناً',
//     processingMinutes: 10,
//     documentsCount: 2,
//     documents: [
//       { name: 'بطاقة الرقم القومي لرب الأسرة', required: true },
//       { name: 'شهادة ميلاد الفرد المراد إضافته', required: true },
//     ],
//     steps: [
//       { order: 1, description: 'الدخول لبوابة التموين الإلكترونية' },
//       { order: 2, description: 'تسجيل الدخول ببيانات البطاقة التموينية' },
//       { order: 3, description: 'اختيار "إضافة فرد" وإدخال بياناته' },
//       { order: 4, description: 'رفع شهادة الميلاد والتأكيد' },
//     ],
//   },
//   {
//     id: 'new-supply-card',
//     title: 'استخراج بطاقة تموين',
//     description: 'استخراج بطاقة تموينية جديدة للأسر المستحقة عبر البوابة الإلكترونية',
//     category: 'supply',
//     icon: 'bi-basket3-fill',
//     estimatedTime: '14 - 30 يوم عمل',
//     fees: 'مجاناً',
//     processingMinutes: 20,
//     documentsCount: 4,
//     documents: [
//       { name: 'بطاقة الرقم القومي لرب الأسرة', required: true },
//       { name: 'عقد إيجار أو وثيقة الإقامة', required: true },
//       { name: 'شهادات ميلاد الأبناء', required: false },
//       { name: 'عقد الزواج', required: false },
//     ],
//     steps: [
//       { order: 1, description: 'التقديم عبر بوابة التموين أو الحضور لمكتب التموين' },
//       { order: 2, description: 'تقديم المستندات المطلوبة للمراجعة' },
//       { order: 3, description: 'انتظار قرار الاعتماد' },
//       { order: 4, description: 'استلام البطاقة التموينية' },
//     ],
//   },
//   {
//     id: 'update-supply-data',
//     title: 'تحديث بيانات البطاقة',
//     description: 'تحديث بيانات البطاقة التموينية عند تغيير العنوان أو الحالة الاجتماعية',
//     category: 'supply',
//     icon: 'bi-basket3-fill',
//     estimatedTime: '3 - 7 أيام عمل',
//     fees: 'مجاناً',
//     processingMinutes: 15,
//     documentsCount: 3,
//     documents: [
//       { name: 'البطاقة التموينية الحالية', required: true },
//       { name: 'بطاقة الرقم القومي', required: true },
//       { name: 'ما يثبت صحة البيانات الجديدة', required: true },
//     ],
//     steps: [
//       { order: 1, description: 'الدخول لبوابة التموين' },
//       { order: 2, description: 'اختيار تحديث البيانات وإدخال التعديلات' },
//       { order: 3, description: 'رفع المستندات الداعمة' },
//       { order: 4, description: 'انتظار الاعتماد والتأكيد' },
//     ],
//   },

  // ── EDUCATION ────────────────────────────────────────────────────────────
//   {
//     id: 'success-statement',
//     title: 'استخراج بيان نجاح',
//     description: 'استخراج بيان نجاح رسمي معتمد من وزارة التربية والتعليم إلكترونياً',
//     category: 'education',
//     icon: 'bi-mortarboard-fill',
//     estimatedTime: '1 - 3 أيام عمل',
//     fees: '30 جنيه',
//     processingMinutes: 10,
//     documentsCount: 2,
//     documents: [
//       { name: 'بطاقة الرقم القومي أو رقم الجلوس', required: true },
//       { name: 'اسم المدرسة والعام الدراسي', required: true },
//     ],
//     steps: [
//       { order: 1, description: 'الدخول لبوابة التعليم الإلكترونية' },
//       { order: 2, description: 'إدخال رقم الجلوس والسنة الدراسية' },
//       { order: 3, description: 'سداد الرسوم' },
//       { order: 4, description: 'تنزيل بيان النجاح معتمداً إلكترونياً' },
//     ],
//   },
//   {
//     id: 'study-certificate',
//     title: 'استخراج شهادة دراسية',
//     description: 'استخراج شهادة دراسية معتمدة لكافة المراحل التعليمية عبر الإنترنت',
//     category: 'education',
//     icon: 'bi-mortarboard-fill',
//     estimatedTime: '3 - 7 أيام عمل',
//     fees: '50 جنيه',
//     processingMinutes: 20,
//     documentsCount: 3,
//     documents: [
//       { name: 'بطاقة الرقم القومي', required: true },
//       { name: 'رقم الجلوس في الامتحان النهائي', required: true },
//       { name: 'تحديد المرحلة التعليمية', required: true },
//     ],
//     steps: [
//       { order: 1, description: 'الدخول لبوابة الشهادات التعليمية' },
//       { order: 2, description: 'اختيار نوع الشهادة والمرحلة الدراسية' },
//       { order: 3, description: 'إدخال البيانات وسداد الرسوم' },
//       { order: 4, description: 'استلام الشهادة بالبريد أو تنزيلها إلكترونياً' },
//     ],
//   },
//   {
//     id: 'results-inquiry',
//     title: 'الاستعلام عن النتائج',
//     description: 'الاستعلام عن نتائج جميع المراحل التعليمية بسهولة ويسر',
//     category: 'education',
//     icon: 'bi-search',
//     estimatedTime: 'فوري',
//     fees: 'مجاناً',
//     processingMinutes: 2,
//     documentsCount: 1,
//     documents: [
//       { name: 'رقم الجلوس أو الرقم القومي', required: true },
//     ],
//     steps: [
//       { order: 1, description: 'الدخول لبوابة نتائج التعليم' },
//       { order: 2, description: 'إدخال رقم الجلوس والمرحلة الدراسية' },
//       { order: 3, description: 'عرض النتيجة فورياً' },
//     ],
//   },

  // ── HEALTH ───────────────────────────────────────────────────────────────
//   {
//     id: 'hospital-appointment',
//     title: 'حجز موعد مستشفى حكومي',
//     description: 'حجز موعد في أقرب مستشفى حكومي إلكترونياً لأي تخصص طبي',
//     category: 'health',
//     icon: 'bi-hospital-fill',
//     estimatedTime: 'فوري',
//     fees: 'مجاناً',
//     processingMinutes: 5,
//     documentsCount: 1,
//     documents: [
//       { name: 'بطاقة الرقم القومي', required: true },
//     ],
//     steps: [
//       { order: 1, description: 'الدخول لبوابة الرعاية الصحية' },
//       { order: 2, description: 'اختيار المستشفى والتخصص المطلوب' },
//       { order: 3, description: 'تحديد الموعد المتاح والتأكيد' },
//       { order: 4, description: 'استلام رسالة تأكيد الحجز' },
//     ],
//   },
//   {
//     id: 'health-insurance-inquiry',
//     title: 'الاستعلام عن التأمين الصحي',
//     description: 'الاستعلام عن بيانات التأمين الصحي ومزايا التغطية المتاحة لك',
//     category: 'health',
//     icon: 'bi-shield-fill-check',
//     estimatedTime: 'فوري',
//     fees: 'مجاناً',
//     processingMinutes: 2,
//     documentsCount: 1,
//     documents: [
//       { name: 'بطاقة الرقم القومي أو رقم التأمين', required: true },
//     ],
//     steps: [
//       { order: 1, description: 'الدخول لبوابة التأمين الصحي' },
//       { order: 2, description: 'إدخال الرقم القومي أو رقم التأمين' },
//       { order: 3, description: 'عرض بيانات التأمين والمزايا المتاحة فورياً' },
//     ],
//   },
//   {
//     id: 'health-certificate',
//     title: 'استخراج شهادة صحية',
//     description: 'استخراج شهادة اللياقة الصحية المعتمدة لأغراض العمل والدراسة',
//     category: 'health',
//     icon: 'bi-file-earmark-medical-fill',
//     estimatedTime: '1 - 3 أيام عمل',
//     fees: '40 جنيه',
//     processingMinutes: 30,
//     documentsCount: 3,
//     documents: [
//       { name: 'بطاقة الرقم القومي', required: true },
//       { name: 'صور شخصية (2 صور)', required: true },
//       { name: 'نتائج الفحوصات الطبية إن طُلبت', required: false },
//     ],
//     steps: [
//       { order: 1, description: 'التوجه لأقرب وحدة صحية أو مستشفى معتمد' },
//       { order: 2, description: 'إجراء الفحص الطبي اللازم' },
//       { order: 3, description: 'سداد الرسوم المقررة' },
//       { order: 4, description: 'استلام الشهادة الصحية المعتمدة' },
//     ],
//   },
];
